### ISSUE TITLE
生成テストスクリプトについて、改行タグ(XXX<br/>XXX)を含むelementを取得しようとしてコード中に改行が入り実行時エラーとなる

### ISSUE THREAD

**Issue by mineo-aya** [latteart-org/latteart#578]
**Describe the bug**
生成テストスクリプトについて、改行タグ(XXX<br/>XXX)を含むelementを取得しようとしてコード中に改行が入り実行時エラーとなる

**Expected behavior**
改行は無視するコードを生成してほしい

**Desktop (please complete the following information):**
 - Browser [chrome80]
 - Version [LatteArt 0.5.0]

**Additional context**
古いバグなので、既に改修済みか、他のissueと同じかご確認お願いします。

**Comment by masaki-tajima** [comment]
#201 も関連．

**Comment by masaki-tajima** [comment]
以下zip内htmlのbuttonタグ
`<button type=“button” onclick="location.href='./test2.html'">ページ&lt;br&gt;リンク2</button>`
でテストしたところ，
`  get ページbrリンク2() { return $('button*=ページ<br>リンク2'); }`
というスクリプトとなり，
`Can't call click on element with selector "button*=ページ<br>リンク2" because element wasn't found`
とのエラーをtest_runner上で確認した．

[test.zip](https://github.com/latteart-org/latteart/files/10455227/test.zip)

**Comment by masaki-tajima** [comment]
#602 へ集約する
